services:
  naming-server:
    image: lenadrocgsi/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - 

networks:
  erudio-network:
    name: erudio-network
    driver: bridge